language: python

python:
  - "2.7"
  - "3.4"

script:
  - tox

install:
  - pip install tox
  - pip install -e .

after_success:
  - coveralls

deploy:
  provider: pypi
  user: smn
  password:
    secure: "sXlDQNG8p+F4y8TKbRVw44uBCzECecgWQLNYcJBObMPoPbp64Ux488kM5RhbYhof0H1W850CKZzW66GQAjay0HS8tp9nPXg35xInPongLFuPzapoOdHtJZa5ub9QnpIs6LifJ/zXP5YDqh8ZUyoD+oFMvMFKjBkVB/NIYMYkyEM="
  on:
    tags: true
    all_branches: true
